
title: "KAYI Code"

collections:
  authors:
    output: true
  locations:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "locations"
    values:
      layout: "location"
  - scope:
      path: ""
    values:
      layout: "default"